### ISSUE TITLE
6.1 - Prototipagem do Painel Administrativo

### ISSUE THREAD

**Issue by KevinFMfatec** [Group-NoName/noname-front#10]
**Descrição:**
Prototipagem feita pelo time de front-end a partir de imagens conceituais feitos pelo PO
Arrumar o wireframe e ver o que é necessário na tela

**Peso:** 3
**Prioridade:** Alta
**Data de início:** 05/09 - 19:00
**Data de término:** 05/09 - 19:45

**DoD**
[ ] Prototipagem feita e aprovada pelo PO

**Comment by ViniciusAndBar** [comment]
![Image](https://user-images.githubusercontent.com/88664252/188519168-4ac83420-1a34-49ae-b52a-d98b88ea536c.png)
