### ISSUE TITLE
9.1 - Prototipagem da Tela de produtos

### ISSUE THREAD

**Issue by KevinFMfatec** [Group-NoName/noname-front#6]
**Descrição:**
Prototipagem feita pelo time de front-end a partir de imagens conceituais feitos pelo PO
Arrumar o wireframe e ver o que é necessário na tela

**Peso:** 3
**Prioridade:** Alta
**Data de início:** 05/04 - 19:50
**Data de início:** 05/04 - 20:10

**DoD**
[ ] Prototipagem feita e aprovada pelo PO

**Comment by ViniciusAndBar** [comment]
![Image](https://user-images.githubusercontent.com/88664252/188535907-8cb77939-e6b8-4650-a4bc-89af1cdf335c.png)
